[package]
name = "wio"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["iocp", "windows", "io", "overlapped"]
repository = "https://github.com/alexcrichton/wio"
homepage = "https://github.com/alexcrichton/wio"
documentation = "http://alexcrichton.com/wio"
description = """
A zero overhead I/O library for Windows, focusing on IOCP and Async I/O
abstractions.
"""

[dependencies]
winapi = "0.2"
kernel32-sys = "0.1"
ws2_32-sys = "0.1"
libc = "0.1"
net2 = { git = "https://github.com/rust-lang-nursery/net2-rs.git" }

[dev-dependencies]
rand = "0.3"

[features]
unstable = []
